### ISSUE TITLE
[bug]: TypeError: n.color.replace is not a function

### ISSUE THREAD

**Issue by rlnt** [srealmoreno/label-sync-action#315]
### Config file of your workflow

```yaml
name: Label Syncer

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-syncer.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Label Sync
        uses: srealmoreno/label-sync-action@v1
        with:
          token: ${{ secrets.LABEL_SYNC_TOKEN }}
          auto-discover-repos: true
          exclude-repos: |
            .github
          account-type: org
          exclude-forked-repos: true
          exclude-archived-repos: true
          exclude-private-repos: true
          exclude-disabled-repos: true
```

### Describe the bug

When the action runs, it prints an error and cancels the workflow:
![](https://i.imgur.com/1WcOuWt.png)

### Expected behavior

It should pass and sync labels.

### Current behavior

It cancels the workflow with an error.

### Logs of the workflow

https://github.com/AlmostReliable/.github/actions/runs/8112547736/

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CONTRIBUTING.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CODE_OF_CONDUCT.md).
